# import win32gui
# import win32process
# import psutil

# def get_user_opened_apps():
#     apps = []
#     def callback(hwnd, _):
#         if win32gui.IsWindowVisible(hwnd) and win32gui.GetWindowText(hwnd):
#             _, pid = win32process.GetWindowThreadProcessId(hwnd)
#             try:
#                 proc = psutil.Process(pid)
#                 apps.append(proc.name())
#             except (psutil.NoSuchProcess, psutil.AccessDenied):
#                 pass
#         return True
#     win32gui.EnumWindows(callback, None)
#     return apps   

# apps = get_user_opened_apps()

# print(apps)

# from AppOpener import open

# print(open("ls"))

from llm.model import ask_llm

prompt = """
From the Given list can you remove the system level application and give me just the user level application which the user cannot acces or even if accesses will cause disryuptiiuon to the system I want to know whichs app I must kill for focus mode and which I should not dare touch
Your output must be the list of apps that are safe to close or operate with and no any other text or anything 
just a refurbished version of the list  
1. 3D VIEWER
2. ACCESS
3. ANDROID STUDIO
4. APPLICATION VERIFIER WOW
5. APPLICATION VERIFIER X
6. BRAVE
7. CALCULATOR
8. CALENDAR
9. CAMERA
10. CHARACTER MAP
11. CISCO PACKET TRACER
12. CISCO PACKET TRACER HELP
13. CLICK TO DO
14. CLOCK
15. COMMAND PROMPT
16. COMPONENT SERVICES
17. COMPUTER MANAGEMENT
18. CONTROL PANEL
19. COPILOT
20. DATABASE COMPARE
21. DEFRAGMENT AND OPTIMIZE DRIVES
22. DEVELOPER COMMAND PROMPT FOR VS
23. DEVELOPER POWERSHELL FOR VS
24. DISCORD
25. DISK CLEANUP
26. DOCKER DESKTOP
27. DOCUMENTATION
28. DOCUMENTATION FOR DESKTOP APPS
29. DOCUMENTATION FOR UWP APPS
30. DOLBY ACCESS
31. EVENT VIEWER
32. EXCEL
33. FAMILY
34. FEEDBACK HUB
35. FIGMA
36. FILE EXPLORER
37. FILMS & TV
38. FN HOTKEYS AND OSD
39. GAME BAR
40. GET HELP
41. GET STARTED
42. GIT BASH
43. GIT CMD
44. GIT FAQS FREQUENTLY ASKED QUESTIONS
45. GIT GUI
46. GIT RELEASE NOTES
47. HOTSPOT SHIELD VPN - WIFI PROXY
48. IDLE PYTHON -BIT
49. INSTALL ADDITIONAL TOOLS FOR NODE JS
50. INTEL GRAPHICS COMMAND CENTER
51. ISCSI INITIATOR
52. JOURNAL
53. LIVE CAPTIONS
54. LIVELY WALLPAPER
55. MAGNIFIER
56. MAIL
57. MAPS
58. MEDIA PLAYER
59. MICROSOFT CLIPCHAMP
60. MICROSOFT COPILOT
61. MICROSOFT EDGE
62. MICROSOFT STORE
63. MICROSOFT TEAMS
64. MICROSOFT TO DO
65. MICROSOFT WHITEBOARD
66. MINECRAFT EDUCATION
67. MIXED REALITY PORTAL
68. MYSQL COMMAND LINE CLIENT
69. MYSQL COMMAND LINE CLIENT - UNICODE
70. MYSQL INSTALLER - COMMUNITY
71. MYSQL SHELL
72. MYSQL WORKBENCH CE
73. NARRATOR
74. NEWS
75. NODE JS COMMAND PROMPT
76. NODE JS DOCUMENTATION
77. NODE JS WEBSITE
78. NOTEPAD
79. NVIDIA CONTROL PANEL
80. NVM
81. ODBC DATA SOURCES -BIT
82. OFFICE LANGUAGE PREFERENCES
83. OLLAMA
84. ON-SCREEN KEYBOARD
85. ONEDRIVE
86. ONENOTE
87. OUTLOOK
88. OUTLOOK CLASSIC
89. PACKET TRACER
90. PACKET TRACER HELP
91. PAINT
92. PERFORMANCE MONITOR
93. PHONE LINK
94. PHOTOS
95. POWER AUTOMATE
96. POWERPOINT
97. PUBLISHER
98. PYTHON -BIT
99. PYTHON MANUALS -BIT
100. PYTHON MODULE DOCS -BIT
101. QODER
102. QT LINGUIST
103. QUICK ASSIST
104. RAINMETER
105. REALTEK AUDIO CONSOLE
106. RECOVERY DRIVE
107. REFERENCE DOCUMENTATION
108. REGISTRY EDITOR
109. RELEASE NOTES
110. REMOTE DESKTOP CONNECTION
111. REPORT A PROBLEM WITH UNITY
112. RESOURCE MONITOR
113. RUN
114. SAMPLE DESKTOP APPS
115. SAMPLE UWP APPS
116. SAVES
117. SERVICES
118. SETTINGS
119. SMART USB BACKUP
120. SNIPPING TOOL
121. SOLITAIRE & CASUAL GAMES
122. SOUND RECORDER
123. SPOTIFY
124. SPREADSHEET COMPARE
125. STEPS RECORDER
126. STICKY NOTES
127. STICKY NOTES NEW
128. SYSTEM CONFIGURATION
129. SYSTEM INFORMATION
130. TASK MANAGER
131. TASK SCHEDULER
132. TERMINAL
133. TOOLS FOR DESKTOP APPS
134. TOOLS FOR UWP APPS
135. TRANSLUCENTTB
136. UBUNTU LTS
137. UNINSTALL NODE JS
138. UNINSTALL ZOOM WORKPLACE
139. UNITY
140. UNITY HUB
141. UNITY RELEASE NOTES
142. VIDEOLAN WEBSITE
143. VISUAL STUDIO
144. VISUAL STUDIO CODE
145. VISUAL STUDIO INSTALLER
146. VLC MEDIA PLAYER
147. VLC MEDIA PLAYER - RESET PREFERENCES AND CACHE FILES
148. VLC MEDIA PLAYER SKINNED
149. VOICE ACCESS
150. WEATHER
151. WHATSAPP
152. WINDOWS APP CERT KIT
153. WINDOWS BACKUP
154. WINDOWS DEFENDER FIREWALL WITH ADVANCED SECURITY
155. WINDOWS MEDIA PLAYER LEGACY
156. WINDOWS MEMORY DIAGNOSTIC
157. WINDOWS POWERSHELL
158. WINDOWS POWERSHELL ISE
159. WINDOWS POWERSHELL ISE X
160. WINDOWS POWERSHELL X
161. WINDOWS SECURITY
162. WINDOWS SOFTWARE DEVELOPMENT KIT
163. WINDOWS TOOLS
164. WORD
165. WSL
166. WSL SETTINGS
167. X NATIVE TOOLS COMMAND PROMPT FOR VS
168. X X CROSS TOOLS COMMAND PROMPT FOR VS
169. XBOX
170. ZOOM WORKPLACE
"""

print(ask_llm(prompt))
