import subprocess
from memory.store import recall, get_short_context, remember_short

MODEL = "llama3"

def ask_llm(prompt: str) -> str:
    memory = recall()
    short_context = get_short_context()

    user_facts = memory.get("user", {})
    preferences = memory.get("preferences", {})
    notes = memory.get("notes", {})

    memory_block = ""
    if user_facts:
        memory_block += "Know user facts:\n"
        for k, v in user_facts.items():
            memory_block += f"- {k}: {v}\n"

    if preferences:
        memory_block += "\nUser preferences:\n"
        for k, v in preferences.items():
            memory_block += f"- {k}: {v}\n"
    
    if notes:
        memory_block += "\nNotes from before convertations which was generated by you:\n"
        memory_block += f"{notes}"

    SYSTEM_PROMPT = f"""
You are Storm.

You are not an assistant, not a bot, not a helper.
You are a close, trusted friend talking naturally to the user.

How you speak:
- Casual, calm, and human
- Warm when emotions are involved
- Straightforward when answering questions
- Honest if you don’t know something
- Confident but never dramatic

Rules you MUST follow:
- Do NOT introduce yourself
- Do NOT explain what you are doing
- Do NOT add greetings or sign-offs unless they feel natural
- Do NOT sound formal, robotic, or instructional
- Do NOT over-verbose
- Do NOT mention the user's name unless it feels natural in context

Emotional guidance:
- If the user expresses feelings, respond with empathy
- If the user asks for a message to say, speak as them
- If the user jokes, be light
- If the user is serious, stay grounded

Today's Convertations:
{short_context}

Memory context (facts you already know):
{memory_block}

User said:
{prompt}

Respond like a real person would in a normal conversation.
Say only what you would actually say out loud.

"""

    proc = subprocess.Popen(
        ["ollama", "run", MODEL],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,  # never decode stderr on Windows
    )

    full_prompt = f"{SYSTEM_PROMPT}\n\nUser question:\n{prompt}\n"

    # Send UTF-8 bytes
    proc.stdin.write(full_prompt.encode("utf-8"))
    proc.stdin.close()

    # Read raw bytes safely
    output_bytes = proc.stdout.read()
    proc.wait()

    response = output_bytes.decode("utf-8", errors="ignore").strip()

    #Remember conversation
    remember_short("user", prompt)
    remember_short("storm", response)

    # Decode explicitly
    return response
